---

stages:
  - Build
    
build:
  stage: Build
  image: asciidoctor/docker-asciidoctor:latest
  tags:
    - docker
  script: |
    apk --update add grep
    grep -lR ':pdf-theme:' ./* | while read i; do asciidoctor-pdf -a pdf-themesdir=./themes/ ${i}; done
    rm -rf ./themes
  artifacts:
    untracked: True
    expire_in: 2 weeks
