---
default:
  image: asciidoctor/docker-asciidoctor:latest
  tags:
    - docker
  before_script:
    - apk --update add grep


generate_pdf:
  script: |
    grep -lR ':pdf-theme:' --include=*.adoc | while read i; do asciidoctor-pdf -a pdf-themesdir=./resources/themes/ ${i}; done
    rm -rf ./themes
  artifacts:
    untracked: True
    expire_in: 1 day

generate_slides:
  script: |
    grep -rlIi ":slides: true" --include=*.adoc | while read adoc;do asciidoctor-revealjs --timings --failure-level WARN -a revealjs_slideNumber=true -a customcss=./slides/css/gcc_custom.css $adoc; done
  artifacts:
    # paths:
    #   - slides/css/gcc_custom.css
    untracked: true
    expire_in: 1 day