---
stages:
  - build

.build:
  image: asciidoctor/docker-asciidoctor:latest
  tags:
    - docker

pdf:
  extends: .build
  script: |
    find ./ -name "*.adoc" | while read i; do asciidoctor --failure-level WARN -v --trace --timings \
    -r asciidoctor-pdf \
    -a pdf-themesdir=./resources/themes \
    ${i}; done
  artifacts:
    paths:
      - resources/images
    untracked: True
    expire_in: 2 weeks

slides:
  extends: .build
  script: |
    git clone -b 3.9.2 --depth 1 https://github.com/hakimel/reveal.js.git
    find ./ -name "*.adoc" | while read i; do asciidoctor --failure-level WARN -v --trace --timings \
    -r asciidoctor-revealjs \
    -a revealjsdir=https://gitlab.com/gacybercenter/theming/-/jobs/$CI_JOB_ID/artifacts/raw/reveal.js \
    -a customcss=https://gitlab.com/gacybercenter/theming/-/jobs/$CI_JOB_ID/artifacts/raw/reveal.js/css/gcc_dark.css \
    ${i}; done  
  artifacts:
    paths:
      - resources/images
      - reveal.js
      - reveal.js/css/gcc_dark.css
      - reveal.js/plugin
    untracked: True
    expire_in: 2 weeks


# html:
#   extends: .build
#   script: |
#     find ./ -name "*.adoc" | while read i; do asciidoctor --failure-level WARN -v --trace --timings \
#     -r asciidoctor-pdf -r asciidoctor-revealjs \
#     -a pdf-themesdir=./resources/themes/ \
#     -a revealjsdir=https://gitlab.com/gacybercenter/theming/-/jobs/$CI_JOB_ID/artifacts/raw/reveal.js \
#     -a customcss=https://gitlab.com/gacybercenter/theming/-/jobs/$CI_JOB_ID/artifacts/raw/reveal.js/css/gcc_dark.css \
#     ${i}; done
#   artifacts:
#     paths:
#       - resources/images
#       - reveal.js
#       - reveal.js/css/gcc_dark.css
#       - reveal.js/plugin
#     untracked: True
#     expire_in: 2 weeks
