---

stages:
  - Lint
  - Build

lint:
  stage: Lint
  image: asciidoctor/docker-asciidoctor:latest
  tags:
    - docker
  script: |
    grep -rlIi ":pdf: true" --include \*.adoc ./*/* | parallel 'asciidoctor-pdf --timings -a allow-uri-read {}'
    
build:
  stage: Build
  image: asciidoctor/docker-asciidoctor:latest
  tags:
    - docker
  script: |
    find ./*/*  -name '*.adoc' | while read i;\
    do theme=$(grep ':theme:' $i | awk '{print $2}');\
    asciidoctor-pdf -a pdf-themesdir=./resources/themes -a pdf-theme=gcc-theme-${theme}.yml ${i} -v; done
  artifacts:
    paths:
      - adoc_pdfs
    expire_in: 2 weeks



  