---

stages:
  - Build
    
build:
  stage: Build
  image: asciidoctor/docker-asciidoctor:latest
  tags:
    - docker
  script: |
    apk --update add grep
    find ./*/*  -name '*.adoc' | while read i;\
    do theme=$(grep ':theme:' $i | awk '{print $2}');\
    asciidoctor-pdf -a pdf-themesdir=./resources/themes -a pdf-theme=gcc-theme-${theme}.yml ${i} -v; done
  artifacts:
    paths:
      - ./*/*
    expire_in: 2 weeks



  