---
default:
  image: asciidoctor/docker-asciidoctor:latest
  tags:
    - docker

stages:
  - Build

build:
  stage: Build
  script: |
    git clone -b 3.9.2 --depth 1 https://github.com/hakimel/reveal.js.git
    find ./ -name "*.adoc" | while read i; do asciidoctor --failure-level WARN -v --trace --timings \
    -a icons=font -a experimental=true -a idprefix="" -a idseparator="-" \
    -r asciidoctor-pdf -r asciidoctor-revealjs -r asciidoctor-diagram \
    -a source-highlighter=highlightjs -a highlightjs-theme=./resources/lib/highlight/styles/gruvbox-dark.min.css -a pdf-themesdir=./resources/themes/ \
    -a customcss=https://gitlab.com/gacybercenter/theming/-/jobs/$CI_JOB_ID/artifacts/raw/resources/css/gcc_dark.css \
    -a revealjsdir=https://gitlab.com/gacybercenter/theming/-/jobs/$CI_JOB_ID/artifacts/raw/reveal.js -a revealjs_transition=slide -a revealjs_slideNumber=true \
    -a revealjs_width=1100 -a revealjs_height=700 -a revealjs_plugins=./resources/revealjs-plugins/revealjs-plugins.js \
    -a docinfo=shared -a toc=macro -a toclevels=1 -a revealjs_plugin_pdf \
    ${i}; done   
  artifacts:
    paths:
      - reveal.js
      - resources
    untracked: True
    expire_in: 2 weeks
