---
default:
  image: asciidoctor/docker-asciidoctor:latest
  tags:
    - docker

stages:
  - Build

build:
  stage: Build
  script: |
    find ./ -name "*.adoc" | while read i; do asciidoctor -r asciidoctor-pdf -r asciidoctor-revealjs \
    -a pdf-themesdir=./resources/themes/ \
    -a revealjsdir=https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.9.2/ \
    -a customcss=https://gitlab.com/gacybercenter/theming/-/jobs/$CI_JOB_ID/artifacts/raw/resources/reveal/css/gcc_custom.css \
    ${i}; done
  artifacts:
    paths:
      - resources/reveal/css/gcc_custom.css
    untracked: True
    expire_in: 2 weeks
